<?php
	// Контроллер-модуль по умолчанию
	define ('DEFAULT_MODULE', 'main');
	
	// Кабинет
	define ('DEFAULT_CABINET', 'cabinet');
	

	// Пути к контроллерам и их шаблонам
	$path = array (
			'main' => 'front/index',
			'page' => 'front/page',
			'news' => 'front/news',
			'about' => 'front/about',
			'rules' => 'front/rules',
			'faq' => 'front/faq',
			'support' => 'front/support',
			'reviews' => 'front/reviews',
			'signup' => 'front/signup',
			'ref' => 'front/ref',
			'login' => 'front/login',
			'logout' => 'front/logout',
			'resetpass' => 'front/resetpass',
			'techwork' => 'front/techwork',
			'lang' => 'front/lang',
			'test' => 'front/test',
			'999' => 'front/stata',
			'cron' => 'front/cron',
			'status' => 'front/status',
			'pay' => 'cabinet/pay',
			'success' => 'cabinet/success',
			'fail' => 'cabinet/fail',
			'cabinet' => 'cabinet/index',
			'add-funds' => 'cabinet/add-funds',
			'deposits' => 'cabinet/deposits',
			'new-deposit' => 'cabinet/new-deposit',
			'withdrawal' => 'cabinet/withdrawal',			
			'info' => 'cabinet/info',
			'friends' => 'cabinet/refsys',
			'wallets' => 'cabinet/wallets',
			'history' => 'cabinet/history',
			'settings' => 'cabinet/settings',
			'changepass' => 'cabinet/changepass',
			'admin' => 'admin/index',
			'show-users' => 'admin/show-users',
			'make-user' => 'admin/make-user',
			'edit-user' => 'admin/edit-user',
			'aka-user' => 'admin/aka-user',
			'make-bot' => 'admin/make-bot',
			'edit-bot' => 'admin/edit-bot',
			'show-bots' => 'admin/show-bots',
			'show-news' => 'admin/show-news',
			'make-news' => 'admin/make-news',
			'edit-news' => 'admin/edit-news',
			'show-pages' => 'admin/show-pages',
			'make-page' => 'admin/make-page',
			'edit-page' => 'admin/edit-page',
			'show-reviews' => 'admin/show-reviews',
			'show-settings' => 'admin/show-settings',
			'approve' => 'admin/approve',
			'canceled' => 'admin/canceled',
			'post' => 'admin/post',
			'delete' => 'admin/delete-object',
			'show-deposits' => 'admin/show-deposits',
			'make-deposit' => 'admin/make-deposit',
			'edit-deposit' => 'admin/edit-deposit',
			'show-operations' => 'admin/show-operations',
			'make-operation' => 'admin/make-operation',
			'edit-operation' => 'admin/edit-operation',
			'show-plans' => 'admin/show-plans',
			'make-plan' => 'admin/make-plan',
			'edit-plan' => 'admin/edit-plan',
			'show-paysys' => 'admin/show-paysys',
			'edit-paysys' => 'admin/edit-paysys',
			'make-bonus' => 'admin/make-bonus',
			'make-penalty' => 'admin/make-penalty'
			);

?>